

CREATE TABLE Skill (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SkillName VARCHAR2(100) NOT NULL,
    ParentId NUMBER,
    CONSTRAINT FK_Skill_Parent
        FOREIGN KEY (ParentId)
        REFERENCES Skill(Id)
);


CREATE OR REPLACE PROCEDURE getChilds(p_SkillName VARCHAR2)
IS
    v_parentId NUMBER;
BEGIN

    SELECT Id
    INTO v_parentId
    FROM Skill
    WHERE SkillName = p_SkillName;

    FOR rec IN
    (
        SELECT
            Id,
            LPAD(' ', LEVEL*3) || SkillName AS SkillName,
            LEVEL AS SkillLevel
        FROM Skill
        START WITH ParentId = v_parentId
        CONNECT BY PRIOR Id = ParentId
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            rec.Id || ' ' || rec.SkillName || ' level=' || rec.SkillLevel
        );
    END LOOP;

END;
/


CREATE OR REPLACE PROCEDURE addChild(
    p_ParentSkillName VARCHAR2,
    p_ChildSkillName VARCHAR2
)
IS
    v_parentId NUMBER;
BEGIN

    IF p_ParentSkillName IS NULL THEN

        INSERT INTO Skill (SkillName, ParentId)
        VALUES (p_ChildSkillName, NULL);

    ELSE

        SELECT Id
        INTO v_parentId
        FROM Skill
        WHERE SkillName = p_ParentSkillName;

        INSERT INTO Skill (SkillName, ParentId)
        VALUES (p_ChildSkillName, v_parentId);

    END IF;

END;
/

DELETE FROM Skill;
COMMIT;


BEGIN

addChild(NULL, 'Programming');

addChild('Programming','Backend');
addChild('Programming','Frontend');
addChild('Programming','System programming');

addChild('Backend','GO');
addChild('Backend','Node.js');
addChild('Backend','Java');

addChild('Frontend','HTML');
addChild('Frontend','CSS');
addChild('Frontend','Sass');
addChild('Frontend','Angular');
addChild('Frontend','Vue');
END;
/

Begin
addChild('HTML', 'xHTML');
addChild('xHTML', 'xxHTML');


END;
/

select * from Skill
BEGIN
    getChilds('Programming');
END;
/


CREATE OR REPLACE PROCEDURE changeParent(
    p_OldParentName VARCHAR2,
    p_NewParentName VARCHAR2
)
IS
    v_oldParent NUMBER;
    v_newParent NUMBER;
BEGIN

    SELECT Id INTO v_oldParent
    FROM Skill
    WHERE SkillName = p_OldParentName;

    SELECT Id INTO v_newParent
    FROM Skill
    WHERE SkillName = p_NewParentName;

    UPDATE Skill
    SET ParentId = v_newParent
    WHERE ParentId = v_oldParent;

END;
/


BEGIN
    changeParent('HTML','System programming');
END;
/